### ISSUE TITLE
Bottom bar

### ISSUE THREAD

**Issue by NickeManarin** [yuv4ik/XFDynamicStatusBarAppearance#1]
It's also possible to change the color of the navigation bar too:

`CrossCurrentActivity.Current.Activity.Window.SetNavigationBarColor(white);`

And the icons like so:

```
CrossCurrentActivity.Current.Activity.Window.DecorView.SystemUiVisibility = isDark ? 
    0 : (StatusBarVisibility)(SystemUiFlags.LightStatusBar | SystemUiFlags.LightNavigationBar);
```

**Comment by yuv4ik** [comment]
Will it work on both iOS and Android?

**Comment by NickeManarin** [comment]
That's only for Android.

**Comment by yuv4ik** [comment]
Thanks for sharing!
